dist: bionic   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"
  - "pypy3.6"
# command to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pandoc
  - source activate testenv
  - pip install -e .
  - pip install git+https://github.com/OpenHydrology/lmoments3.git # temporary until this is correcly updated on PyPI
  - pip install -e .[dev]
# command to run tests
script:
  - pytest -v